/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AsyncDataMonitorInterface extends Interface {
    getFunction(nameOrSignature: "alertCooldown" | "lastAlertTime" | "recordData" | "threshold" | "updateThreshold"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AlertTriggered" | "DataRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'alertCooldown', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastAlertTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordData', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'threshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateThreshold', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'alertCooldown', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastAlertTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'threshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateThreshold', data: BytesLike): Result;
  }

  
    export namespace AlertTriggeredEvent {
      export type InputTuple = [value: BigNumberish, timestamp: BigNumberish, message: string];
      export type OutputTuple = [value: bigint, timestamp: bigint, message: string];
      export interface OutputObject {value: bigint, timestamp: bigint, message: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DataRecordedEvent {
      export type InputTuple = [value: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [value: bigint, timestamp: bigint];
      export interface OutputObject {value: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AsyncDataMonitor extends BaseContract {
    
    connect(runner?: ContractRunner | null): AsyncDataMonitor;
    waitForDeployment(): Promise<this>;

    interface: AsyncDataMonitorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    alertCooldown: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lastAlertTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    recordData: TypedContractMethod<
      [dataValue: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    threshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateThreshold: TypedContractMethod<
      [_newThreshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'alertCooldown'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastAlertTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recordData'): TypedContractMethod<
      [dataValue: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'threshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateThreshold'): TypedContractMethod<
      [_newThreshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AlertTriggered'): TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
getEvent(key: 'DataRecorded'): TypedContractEvent<DataRecordedEvent.InputTuple, DataRecordedEvent.OutputTuple, DataRecordedEvent.OutputObject>;

    filters: {
      
      'AlertTriggered(int256,uint256,string)': TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
      AlertTriggered: TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
    

      'DataRecorded(int256,uint256)': TypedContractEvent<DataRecordedEvent.InputTuple, DataRecordedEvent.OutputTuple, DataRecordedEvent.OutputObject>;
      DataRecorded: TypedContractEvent<DataRecordedEvent.InputTuple, DataRecordedEvent.OutputTuple, DataRecordedEvent.OutputObject>;
    
    };
  }