/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CertificatoreMultimetroInterface extends Interface {
    getFunction(nameOrSignature: "autorizzati" | "certificaRilevazione" | "hashEsistenti" | "owner" | "registro"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DatoCertificato"): EventFragment;

    encodeFunctionData(functionFragment: 'autorizzati', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'certificaRilevazione', values: [string, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'hashEsistenti', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registro', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'autorizzati', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certificaRilevazione', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hashEsistenti', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registro', data: BytesLike): Result;
  }

  
    export namespace DatoCertificatoEvent {
      export type InputTuple = [deviceId: string, timestamp: BigNumberish, fileHash: BytesLike];
      export type OutputTuple = [deviceId: string, timestamp: bigint, fileHash: string];
      export interface OutputObject {deviceId: string, timestamp: bigint, fileHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CertificatoreMultimetro extends BaseContract {
    
    connect(runner?: ContractRunner | null): CertificatoreMultimetro;
    waitForDeployment(): Promise<this>;

    interface: CertificatoreMultimetroInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    autorizzati: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    certificaRilevazione: TypedContractMethod<
      [_deviceId: string, _timestamp: BigNumberish, _fileHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    hashEsistenti: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registro: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, string, boolean] & {deviceId: string, timestamp: bigint, fileHash: string, certificatore: string, elaborato: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'autorizzati'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'certificaRilevazione'): TypedContractMethod<
      [_deviceId: string, _timestamp: BigNumberish, _fileHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hashEsistenti'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registro'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, string, boolean] & {deviceId: string, timestamp: bigint, fileHash: string, certificatore: string, elaborato: boolean }],
      'view'
    >;

    getEvent(key: 'DatoCertificato'): TypedContractEvent<DatoCertificatoEvent.InputTuple, DatoCertificatoEvent.OutputTuple, DatoCertificatoEvent.OutputObject>;

    filters: {
      
      'DatoCertificato(string,uint256,bytes32)': TypedContractEvent<DatoCertificatoEvent.InputTuple, DatoCertificatoEvent.OutputTuple, DatoCertificatoEvent.OutputObject>;
      DatoCertificato: TypedContractEvent<DatoCertificatoEvent.InputTuple, DatoCertificatoEvent.OutputTuple, DatoCertificatoEvent.OutputObject>;
    
    };
  }