/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DataCalculatorInterface extends Interface {
    getFunction(nameOrSignature: "calculateAverage" | "calculateMax" | "calculateMin"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'calculateAverage', values: [BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'calculateMax', values: [BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'calculateMin', values: [BigNumberish[]]): string;

    decodeFunctionResult(functionFragment: 'calculateAverage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateMax', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateMin', data: BytesLike): Result;
  }

  

  export interface DataCalculator extends BaseContract {
    
    connect(runner?: ContractRunner | null): DataCalculator;
    waitForDeployment(): Promise<this>;

    interface: DataCalculatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    calculateAverage: TypedContractMethod<
      [data: BigNumberish[], ],
      [bigint],
      'view'
    >
    

    
    calculateMax: TypedContractMethod<
      [data: BigNumberish[], ],
      [bigint],
      'view'
    >
    

    
    calculateMin: TypedContractMethod<
      [data: BigNumberish[], ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'calculateAverage'): TypedContractMethod<
      [data: BigNumberish[], ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateMax'): TypedContractMethod<
      [data: BigNumberish[], ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateMin'): TypedContractMethod<
      [data: BigNumberish[], ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }