/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ElaboratoreDatiInterface extends Interface {
    getFunction(nameOrSignature: "cacheRisultati" | "elaboraMediaTensione"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CalcoloEseguito" | "RisultatoRecuperatoDallaCache"): EventFragment;

    encodeFunctionData(functionFragment: 'cacheRisultati', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'elaboraMediaTensione', values: [BytesLike, string]): string;

    decodeFunctionResult(functionFragment: 'cacheRisultati', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'elaboraMediaTensione', data: BytesLike): Result;
  }

  
    export namespace CalcoloEseguitoEvent {
      export type InputTuple = [fileHash: BytesLike, risultatoJSON: string];
      export type OutputTuple = [fileHash: string, risultatoJSON: string];
      export interface OutputObject {fileHash: string, risultatoJSON: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RisultatoRecuperatoDallaCacheEvent {
      export type InputTuple = [fileHash: BytesLike, risultatoJSON: string];
      export type OutputTuple = [fileHash: string, risultatoJSON: string];
      export interface OutputObject {fileHash: string, risultatoJSON: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ElaboratoreDati extends BaseContract {
    
    connect(runner?: ContractRunner | null): ElaboratoreDati;
    waitForDeployment(): Promise<this>;

    interface: ElaboratoreDatiInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cacheRisultati: TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >
    

    
    elaboraMediaTensione: TypedContractMethod<
      [_fileHash: BytesLike, _valoreCalcolato: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cacheRisultati'): TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'elaboraMediaTensione'): TypedContractMethod<
      [_fileHash: BytesLike, _valoreCalcolato: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CalcoloEseguito'): TypedContractEvent<CalcoloEseguitoEvent.InputTuple, CalcoloEseguitoEvent.OutputTuple, CalcoloEseguitoEvent.OutputObject>;
getEvent(key: 'RisultatoRecuperatoDallaCache'): TypedContractEvent<RisultatoRecuperatoDallaCacheEvent.InputTuple, RisultatoRecuperatoDallaCacheEvent.OutputTuple, RisultatoRecuperatoDallaCacheEvent.OutputObject>;

    filters: {
      
      'CalcoloEseguito(bytes32,string)': TypedContractEvent<CalcoloEseguitoEvent.InputTuple, CalcoloEseguitoEvent.OutputTuple, CalcoloEseguitoEvent.OutputObject>;
      CalcoloEseguito: TypedContractEvent<CalcoloEseguitoEvent.InputTuple, CalcoloEseguitoEvent.OutputTuple, CalcoloEseguitoEvent.OutputObject>;
    

      'RisultatoRecuperatoDallaCache(bytes32,string)': TypedContractEvent<RisultatoRecuperatoDallaCacheEvent.InputTuple, RisultatoRecuperatoDallaCacheEvent.OutputTuple, RisultatoRecuperatoDallaCacheEvent.OutputObject>;
      RisultatoRecuperatoDallaCache: TypedContractEvent<RisultatoRecuperatoDallaCacheEvent.InputTuple, RisultatoRecuperatoDallaCacheEvent.OutputTuple, RisultatoRecuperatoDallaCacheEvent.OutputObject>;
    
    };
  }