/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CertificatoreMultimetro } from './CertificatoreMultimetro.js';
export type { ElaboratoreDati } from './ElaboratoreDati.js';
export * as factories from './factories/index.js';
export { CertificatoreMultimetro__factory } from './factories/CertificatoreMultimetro__factory.js';
export { ElaboratoreDati__factory } from './factories/ElaboratoreDati__factory.js';