/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CertificatoreMultimetro__factory } from './CertificatoreMultimetro__factory.js';
export { ElaboratoreDati__factory } from './ElaboratoreDati__factory.js';